title: Jason Figueroa
email: jason.figueroa2@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jasonfigueroa_
github_username:  jasonfigueroa

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  # - jekyll-include-cache

include:
  - _pages

defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false # this was enabled but on narrow view would display a follow button
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: false
