title: Jason Figueroa
email: jason.figueroa2@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  # - jekyll-include-cache

include:
  - _pages
  - assets

author:
  name   : "Jason Figueroa"
  avatar : "/assets/images/headshot.png"
  bio    : "I'm a naturally curious computer programmer based near Nashville, TN."
  location: "Clarksville, TN"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/jasonfigueroa_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: https://linkedin.com/jason-figueroa-b59a3798
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jasonfigueroa
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:jason.figueroa2@gmail.com"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/jasonfigueroa_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: https://linkedin.com/jason-figueroa-b59a3798
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jasonfigueroa
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:jason.figueroa2@gmail.com"

defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: false
